### ISSUE TITLE
Update to 1.18 checklist

### ISSUE THREAD

**Issue by copygirl** [copygirl/humanity-modpack#1]
- [x] Adorn
- [x] Alternate Current
- [x] AppleSkin
- [ ] Artifacts
- [x] Axes Are Weapons
- [ ] AxolotlViewer
- [x] Bedspreads
- [ ] Bee Buddies
- [ ] YUNG's Better Dungeons
- [ ] Better Enchanted Books
- [ ] BetterEnd
- [ ] YUNG's Better Mineshafts
- [x] Better Recipe Book
- [ ] YUNG's Better Strongholds
- [x] Blur
- [ ] Charm ([1.18.x branch](https://github.com/svenhjol/Charm/tree/1.18.x))
- [x] Chat Heads
- [x] ChickensShed
- [x] ClickThrough
- [x] Cammie's Combat Tweaks
- [x] Detail Armor Bar
- [x] Double Jump Mod
- [x] Ducts
- [x] EasyAutoCrafting
- [x] When Dungeons Arise
- [x] Fabrication
- [x] Falling Leaves
- [x] Farmer's Delight
- [ ] Figura ([1.18 branch](https://github.com/Blancworks/Figura/tree/1.18))
- [ ] Full Slabs
- [x] First-person Model
- [ ] Gilded Armor
- [x] Grind Enchantments
- [ ] Here be no Dragons!
- [x] Immersive Portals
- [x] Independent Pets
- [x] Inventory Hotswap
- [x] Inventory Totem
- [x] InvMove
- [x] Iris Shaders
- [ ] Iron Bundles
- [x] Item Model Fix
- [x] ItemScroller
- [x] KubeJS
- [ ] Lakeside
- [x] LambdaControls
- [x] LinkedStorage
- [x] Lithium
- [ ] Minef*ck
- [x] ModMenu
- [ ] Mooblooms
- [x] Mo' Structures
- [x] Mouse Wheelie
- [x] Not Enough Animations
- [x] OverpoweredMending
- [x] ~~Pitch Dark~~ (now in Vanilla)
- [x] Presence Footsteps
- [x] Quick Shulker
- [x] Quilt Loading Screen
- [x] Rat's Mischief
- [x] Repurposed Structures
- [x] Reroll
- [x] Respawnable Pets
- [x] Roughly Enough Items
- [ ] RSWires
- [x] ShulkerBoxTooltip
- [ ] Sky Villages
- [x] Sound Physics Remastered
- [ ] StackablePotions
- [x] Starlight
- [ ] Status Effect Timer
- [ ] Stockpile
- [x] Stoneholm
- [x] Sync
- [x] Tax Free Levels
- [x] Universal Ores
- [ ] ValleyCraft
- [x] Victus
- [ ] Roundaround's Villager Converting
- [x] Simple Voice Chat
- [x] Wolves With Armor
